# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: selfsigned
# spec:
#   selfSigned: {}
# ---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain1.com 
spec:
  isCA: true
  commonName: domain1.com 
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
# ---
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: domain1-issuer
# spec:
#   ca:
#     secretName: root-secret
